# apps/traefik/helm-release.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: traefik
spec:
  chart: traefik
  repo: https://helm.traefik.io/traefik
  targetNamespace: traefik
  version: v24.0.*
  valuesContent: |-
    additionalArguments:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.cloudflare.acme.email=christopher.michael.shaw@gmail.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.delaybeforecheck=5"
    ports:
      web:
        port: 80
        expose: true
      websecure:
        port: 443
        expose: true
    env:
      - name: CF_API_EMAIL
        value: christopher.michael.shaw@gmail.com
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: cloudflare-api
            key: api-token
    persistence:
      enabled: true
      name: traefik-data
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: longhorn

