apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
spec:
  acme:
    email: christopher.michael.shaw@gmail.com
    solvers:
      - dns01:
          cloudflare:
            email: christopher.michael.shaw@gmail.com
