targets:
  - name: homelab-target
    clusterSelector:
      matchLabels:
        Env: homelab
    ignore:
      - apiVersion: apps/v1
        kind: Deployment
        name: harvester
      - apiVersion: apps/v1
        kind: Deployment
        name: harvester-webhook
      - apiVersion: apps/v1
        kind: Deployment
        name: harvester-node-manager-webhook
      - apiVersion: apps/v1
        kind: Deployment
        name: harvester-network-controller-manager
      - apiVersion: apps/v1
        kind: DaemonSet
        name: harvester-node-disk-manager
      - apiVersion: apps/v1
        kind: DaemonSet
        name: harvester-networkfs-manager
      - apiVersion: apps/v1
        kind: DaemonSet
        name: harvester-whereabouts
      - apiVersion: apps/v1
        kind: DaemonSet
        name: longhorn-manager
      - apiVersion: kubevirt.io/v1
        kind: KubeVirt
        name: kubevirt

resources:
  - apps/cert-manager
  - apps/traefik
  - secrets
