apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-homelab
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 24.0.*
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values-homelab
      valuesKey: traefik-values-homelab.yaml