name: Validate Kustomize and SOPS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      SOPS_AGE_KEY: ${{ secrets.AGE_PRIVATE_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gpg jq

          # Install sops
          curl -sSfL https://github.com/getsops/sops/releases/latest/download/sops-linux-amd64 -o /usr/local/bin/sops
          chmod +x /usr/local/bin/sops

          # Install kustomize (dynamic version detection)
          KUSTOMIZE_VERSION=$(curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases/latest | jq -r '.tag_name')
          curl -sSfL "https://github.com/kubernetes-sigs/kustomize/releases/download/${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION#v}_linux_amd64.tar.gz" \
            | tar -xz -C /usr/local/bin

          # Install yq
          curl -sSfL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Decrypt secrets and validate SOPS
        run: |
          find . -type f -name '*.yaml' | while read -r file; do
            if grep -q 'sops:' "$file"; then
              echo "Validating $file"
              sops -d "$file" >/dev/null
            fi
          done

      - name: Validate Kustomize overlays
        run: |
          for dir in clusters/*/*; do
            if [ -f "$dir/kustomization.yaml" ]; then
              echo "Validating kustomization in $dir"
              kustomize build "$dir" >/dev/null
            fi
          done
